# Taking Matix Input from User

In [1]:
import numpy as np

L1 = []
L2 = []

print("Enter Matrix 1 Elements: ")

for i in range(0, 9):
    L1.append(eval(input()))

M1 = np.array(L1)
M1 = M1.reshape(3, 3)

print("Printing First Matrix .....")

print(M1)

print("Enter Matrix 2 Elements: ")

for i in range(0, 9):
    L2.append(eval(input()))

M2 = np.array(L2)
M2 = M2.reshape(3, 3)

print("Printing Second Matrix .....")

print(M2)

Enter Matrix 1 Elements: 
1
2
3
4
5
6
7
8
9
Printing First Matrix .....
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Enter Matrix 2 Elements: 
10
11
12
13
14
15
16
17
18
Printing Second Matrix .....
[[10 11 12]
 [13 14 15]
 [16 17 18]]


# Matrix Addition, Subtraction and Division

In [2]:
M3 = np.add(M1, M2)
print("Addition of both the Matrices is \n", M3)

M4 = np.subtract(M2, M1)
print("Subtraction of both the Matrices is \n", M4)

M5 = np.divide(M2, M1)
print("Division between both the Matrices is \n", M5)

Addition of both the Matrices is 
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
Subtraction of both the Matrices is 
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
Division between both the Matrices is 
 [[10.          5.5         4.        ]
 [ 3.25        2.8         2.5       ]
 [ 2.28571429  2.125       2.        ]]


# Matrix Multiplication using loop

In [3]:
L3 = []

M6 = np.zeros((3, 3), np.int32)

for i in range(0, 3):
    for j in range(0, 3):
        for k in range(0, 3):
            M6[i][j] += M1[i][k] * M2[k][j]

print(M6)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


# Matrix Multiplication without loop

In [4]:
M7 = np.matmul(M1, M2)

print(M7)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


# Matrix Transpose

In [5]:
M8 = M1.transpose()
M9 = M2.transpose()

print("Transpose of the First Matrix which you have entered ....")
print(M8)

print("Transpose of the Second Matrix which you have entered ....")
print(M9)

Transpose of the First Matrix which you have entered ....
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of the Second Matrix which you have entered ....
[[10 13 16]
 [11 14 17]
 [12 15 18]]
